# tasks/server.yml -- Tasks specific for the collectd server
---

- name: Server | Ensure data directory exists
  file:
    path: "{{ collectd_rrdtool_data_dir }}"
    state: directory
    owner: root
    mode: '0755'
  tags: collectd

- name: Common | Install authentication file
  template:
    src: etc_collectd_auth.j2
    dest: "{{ collectd_auth_file }}"
    owner: root
    mode: '0600'
  tags: collectd

- name: Server | Install rrdtool configuration file
  template:
    src: etc_collectd_d_rrdtool.conf.j2
    dest: "{{ collectd_include_dir }}/rrdtool.conf"
    owner: root
    mode: '0644'
    validate: "collectd -t -C %s"
  notify: restart collectd
  tags: collectd
