# roles/collectd/tasks/server.yml
# Tasks specific for the collectd server
---

- name: Ensure data directory exists
  file:
    path: "{{ collectd_rrdtool_data_dir }}"
    state: directory
  tags: collectd

- name: Install rrdtool configuration file
  template:
    src: etc_collectd_d_rrdtool.conf.j2
    dest: "{{ collectd_include_dir }}/rrdtool.conf"
    validate: "collectd -t -C %s"
  notify: restart collectd
  tags: collectd

