# tasks/web.yml -- Installation of collectd-web
---

- name: Web | Install packages for collectd-web
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ collectd_web_packages }}"
  tags: collectd

- name: Web | Ensure web server is started
  service:
    name: "{{ collectd_web_service }}"
    state: started
    enabled: true
  tags: collectd

- name: Web | Install Apache configuration file
  template:
    src: etc_httpd_conf.d_collectd.conf.j2
    dest: "{{ collectd_web_conf_dir }}/collectd.conf"
    owner: root
    mode: '0644'
  notify: restart httpd
  tags: collectd
