# vi: set ft=ruby

require 'rbconfig'

HOST_NAME = 'collectd'
VAGRANTFILE_API_VERSION = '2'
# The number of hosts that send their data to the collectd server
#  Assumed to be at most 9.
NUM_CLIENTS = 2

def client_names(base_name, num_clients)
  names = []
  (1..num_clients).each do |client_id|
    names << base_name + client_id.to_s
  end
  names
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'bento/centos-7.5'

  # Server
  server_name = HOST_NAME + 'srv'

  config.vm.define server_name do |node|
    node.vm.hostname = server_name
    node.vm.network 'private_network', ip: '192.168.56.40'
  end

  (1..NUM_CLIENTS).each do |client_id|
    client_name = HOST_NAME + 'cln' + client_id.to_s
    config.vm.define client_name do |node|
      node.vm.hostname = client_name
      node.vm.network 'private_network', ip: '192.168.56.4' + client_id.to_s
    end
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.groups = {
      "server"  => [server_name],
      "clients" => client_names(HOST_NAME + 'cln', NUM_CLIENTS)
    }
    ansible.playbook = 'test.yml'
  end

end

