---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  yamllint .
  ansible-lint -v .

platforms:
  - name: srv
    box: bento/centos-7
    memory: 2048
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.40"
  - name: cl1
    box: bento/centos-7
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.41"
  - name: cl2
    box: bento/centos-7
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.42"

provisioner:
  name: ansible

verifier:
  name: ansible
